import React, { useEffect, useRef, useState } from "react";
import { Alert, Box, Button, CircularProgress, MenuItem, Stack, TextField, Typography } from "@mui/material";
import axios from "axios";
import { useNavigate, useSearchParams } from "react-router-dom";
import { getDefaultAreaPath } from "../utils/areaRouting";
import { useLanguage } from "../i18n/LanguageContext";

export default function GoogleCallbackPage({ onComplete }) {
  const { t } = useLanguage(); const [params] = useSearchParams(); const navigate = useNavigate(); const [code] = useState(params.get("code") || ""); const exchangeStarted = useRef(false); const [onboarding, setOnboarding] = useState(false); const [role, setRole] = useState("mentee"); const [details, setDetails] = useState({ background: "", jobTitle: "", workplace: "", mentoringTopics: "", meetingCapacity: 1, meetingDurationMinutes: 45 }); const [loading, setLoading] = useState(Boolean(code)); const [error, setError] = useState(params.get("error") === "cancelled" ? t("auth.googleCancelled") : params.get("error") === "provider" ? t("auth.googleProviderError") : params.get("error") ? t("auth.googleInvalidState") : "");
  // The callback code is intentionally consumed once on mount.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { if (exchangeStarted.current) return; exchangeStarted.current = true; if (!code) { setError(t("auth.googleError")); setLoading(false); return; } axios.post("/api/auth/google/exchange", { code }).then(({ data }) => { if (data.needsOnboarding) { setCodeForOnboarding(data.onboardingCode); setOnboarding(true); } else { onComplete(data.user, data.token); navigate(getDefaultAreaPath(data.user)); } }).catch(() => setError(t("auth.googleError"))).finally(() => setLoading(false)); }, []);
  const [onboardingCode, setCodeForOnboarding] = useState("");
  const submit = async (event) => { event.preventDefault(); setLoading(true); try { const response = await axios.post("/api/auth/google/complete", { code: onboardingCode, role, details: { ...details, mentoringTopics: details.mentoringTopics.split(",").map((x) => x.trim()).filter(Boolean) } }); onComplete(response.data.user, response.data.token); navigate(getDefaultAreaPath(response.data.user)); } catch (_) { setError(t("auth.googleOnboardingError")); } finally { setLoading(false); } };
  if (loading && !onboarding) return <Box sx={{ py: 12, textAlign: "center" }}><CircularProgress /></Box>;
  if (error && !onboarding) return <Box sx={{ maxWidth: 480, mx: "auto", py: 8, px: 3 }}><Alert severity="error">{error}</Alert><Button onClick={() => navigate("/")} sx={{ mt: 2 }}>{t("common.backHome")}</Button></Box>;
  return <Box sx={{ maxWidth: 480, mx: "auto", py: 8, px: 3 }}><Typography variant="h5" sx={{ mb: 3 }}>{t("auth.googleOnboardingTitle")}</Typography><Box component="form" onSubmit={submit}><Stack spacing={2}><TextField select label={t("auth.googleRole")} value={role} onChange={(e) => setRole(e.target.value)}><MenuItem value="mentee">{t("roles.mentee")}</MenuItem><MenuItem value="mentor">{t("roles.mentor")}</MenuItem></TextField><TextField label={t("auth.backgroundRequired")} value={details.background} onChange={(e) => setDetails({ ...details, background: e.target.value })} required fullWidth />{role === "mentor" && <><TextField label={t("auth.currentJobOptional")} value={details.jobTitle} onChange={(e) => setDetails({ ...details, jobTitle: e.target.value })} /><TextField label={t("auth.companyOptional")} value={details.workplace} onChange={(e) => setDetails({ ...details, workplace: e.target.value })} /><TextField label={t("auth.mentoringTopics")} value={details.mentoringTopics} onChange={(e) => setDetails({ ...details, mentoringTopics: e.target.value })} required /><TextField type="number" label={t("auth.meetingCount")} value={details.meetingCapacity} onChange={(e) => setDetails({ ...details, meetingCapacity: e.target.value })} required /></>}{error && <Alert severity="error">{error}</Alert>}<Button type="submit" variant="contained" disabled={loading}>{loading ? <CircularProgress size={22} /> : t("auth.googleContinue")}</Button></Stack></Box></Box>;
}
